-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQguPyXwzdyYYkh9op2
qWD4q5KUWv2NdrHoFj1BMf5kzoegCgYIKoZIzj0DAQehRANCAARs0JNG6nRWgEme
CuTGJca8pJtyd8GQISK+MCYaaut8qiRYt9iZ6ejrw6Ok0BqCCYvdwBucIgvStW+S
JunwUEY5
-----END PRIVATE KEY-----